version: "3.9"

services:
  robbie_robot_tts:
    build:
      context: ../
      dockerfile: container_robbie/robbie_9000/Dockerfile
    depends_on:
      - marytts
    restart: no
    networks:
      - robbie_net
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "/robbie/code_robbie:/robbie/code_robbie"
      - "$HOME/.config/rhasspy/profiles:/profiles"
      - "/etc/localtime:/etc/localtime:ro"
      - "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    ports:
      - "8000:8000"
      - "12101:12101"
      - "12183:12183"

#    command: --user-profiles /profiles --profile de

#    volumes:
#      - /robbie/code_robbie:/robbie/code_robbie
#      - "/etc/asound.conf:/etc/asound.conf"
#      - "/var/run/dbus:/var/run/dbus"
#      - "/etc/machine-id:/etc/machine-id"
##      - "/run/pulse:/run/pulse"
#      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
#    environment:
#      - PULSE_SERVER=unix:/run/user/1000/pulse/native
#      - PULSE_COOKIE=/run/pulse/cookie
#      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
#      - PULSE_COOKIE_DATA=

  marytts:
    image: synesthesiam/marytts:5.2
    ports:
      - '59125:59125'
    restart: on-failure
    networks:
      - robbie_net
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "/etc/asound.conf:/etc/asound.conf"
      - "/var/run/dbus:/var/run/dbus"
      - "/etc/machine-id:/etc/machine-id"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE_DATA=

networks:
  robbie_net: