version: "3.9"

services:
  pi4_base:
    build:
      context: ../container_robbie/pi4_base/Dockerfile
      dockerfile: Dockerfile.base
    image: pi4_base:latest
    volumes:
      - "/robbie/code_robbie:/robbie/code_robbie"

  robbie_robot_tts:
    build:
      context: ../
      dockerfile: container_robbie/robbie_9000/Dockerfile
    depends_on:
      - marytts
      - eye_manager
    privileged: true
    restart: no
    networks:
      - robbie_net
    devices:
      # audio
      - "/dev/snd:/dev/snd"
      - "/dev/bus/usb:/dev/bus/usb"

    volumes:
#      - "/robbie/code_robbie:/robbie/code_robbie"

      # audio
      - "$HOME/.config/rhasspy/profiles:/profiles"
      - "/etc/localtime:/etc/localtime:ro"
      - "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "/run/user/1000/pulse:/run/user/1000/pulse"

      # SPI (display)
      - "/sys:/sys"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    ports:
      - "8000:8000"
      - "12101:12101"
      - "12183:12183"

  eye_manager:
    build:
      context: ../
      dockerfile: container_robbie/eye_manager/Dockerfile
    privileged: true
    restart: on-failure
    networks:
        - robbie_net
    devices:
      # SPI (display)
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev1.0:/dev/spidev1.0"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem"
    volumes:
      - "/robbie/code_robbie:/robbie/code_robbie"
        # SPI (display)
      - "/sys:/sys"

  marytts:
    image: synesthesiam/marytts:5.2
    ports:
      - '59125:59125'
    restart: on-failure
    networks:
      - robbie_net
    entrypoint: "bash -c 'java -Dlog4j.configuration=file:/marytts/log4j.properties -Xmx1g -cp lib/*:bin/* marytts.server.Mary >/dev/null 2>&1'"

networks:
  robbie_net: