version: "3.9"

services:
  robbie_robot_tts:
    build:
      context: ../
      dockerfile: container_robbie/robbie_9000/Dockerfile
    depends_on:
      - marytts
    privileged: true
    restart: no
    networks:
      - robbie_net
    devices:
      # audio
      - "/dev/snd:/dev/snd"
      - "/dev/bus/usb:/dev/bus/usb"

      # SPI (display)
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
      - "/dev/mem:/dev/mem"

      - "/dev/gpiomem"

#    group:
#      - gpio
#      - spi
    volumes:
      - "/robbie/code_robbie:/robbie/code_robbie"

      # audio
      - "$HOME/.config/rhasspy/profiles:/profiles"
      - "/etc/localtime:/etc/localtime:ro"
      - "$HOME/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "/run/user/1000/pulse:/run/user/1000/pulse"

      # SPI (display)
      - "/sys:/sys"
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    ports:
      - "8000:8000"
      - "12101:12101"
      - "12183:12183"

  marytts:
    image: synesthesiam/marytts:5.2
    ports:
      - '59125:59125'
    restart: on-failure
    networks:
      - robbie_net
    entrypoint: "bash -c 'java -Dlog4j.configuration=file:/marytts/log4j.properties -Xmx1g -cp lib/*:bin/* marytts.server.Mary >/dev/null 2>&1'"

networks:
  robbie_net: