FROM synesthesiam/marytts:5.2
COPY marytts-log4j.properties /marytts/log4j.properties
#CMD ["bash", "-c", "java -Dlog4j.logger.marytts=WARN -Xmx1g -cp lib/*:bin/* marytts.server.Mary >/dev/null 2>&1"]
#entrypoint "bash -c 'java -Dlog4j.configuration=file:/marytts/log4j.properties -Xmx1g -cp lib/*:bin/* marytts.server.Mary >/dev/null 2>&1'"
